Feature/about
Alexander0Yusov/team-proj pull request #4
Opened 2023-01-12 19:50 UTC by alina-marhaniia

2023-01-12 21:44 UTC, Alexander0Yusov requested changes
в стили не смотрел. подшамань их согласно классов в html документе. должны убавиться стили заголовков

2023-01-12 21:44 UTC, Alexander0Yusov commented on src/index.html
>      <!-- ❗️❗️❗️ Add partials like so for every page -->
17 и 18 строки удали

2023-01-12 21:44 UTC, Alexander0Yusov commented on src/partials/about.html
> +    <p class="about__label">tradition and love</p>
примени класс претайтл, если его недостаточно то класс модификатор добавь

2023-01-12 21:44 UTC, Alexander0Yusov commented on src/partials/about.html
> +    <h1 id="about" class="about__title">how it’s made?</h1>
используй готовый класс тайтл-н2. если его недостаточно то класс модификатор добавь.  замени на тег н2

2023-01-13 13:12 UTC, alina-marhaniia commented on src/index.html
>      <!-- ❗️❗️❗️ Add partials like so for every page -->
Done

2023-01-13 13:24 UTC, alina-marhaniia commented on src/partials/about.html
> +    <p class="about__label">tradition and love</p>
Done

2023-01-13 15:57 UTC, Alexander0Yusov approved these changes

2023-01-13 16:03 UTC, merged

2023-01-13 16:08 UTC, Alexander0Yusov commented
well done

2023-01-13 16:08 UTC, Alexander0Yusov commented
well done