block products
Alexander0Yusov/team-proj pull request #6
Opened 2023-01-12 22:46 UTC by chell-iz-naroda

2023-01-12 23:23 UTC, Alexander0Yusov requested changes

2023-01-12 23:23 UTC, Alexander0Yusov commented on src/partials/produts.html
> +    <h2 class="products__title link">products</h2>
класс title-h2 уже существует. примени. если не идеально подходит то переопредели или дополни своим доп классом

2023-01-12 23:23 UTC, Alexander0Yusov commented on src/partials/produts.html
> +    <p class="products__paragraph link">100% natural</p>
класс pre-title уже существует. примени. если не идеально подходит то переопредели или дополни своим доп классом

2023-01-12 23:23 UTC, Alexander0Yusov commented on src/sass/layouts/_products.scss
> +    background-image: url(../images/ice-cream-back.jpg);
для ретины другая картинка нужна

2023-01-13 09:51 UTC, chell-iz-naroda commented on src/partials/produts.html
> +    <h2 class="products__title link">products</h2>
Добавлено

2023-01-13 09:51 UTC, chell-iz-naroda commented on src/partials/produts.html
> +    <p class="products__paragraph link">100% natural</p>
Добавлено

2023-01-13 09:51 UTC, chell-iz-naroda commented on src/sass/layouts/_products.scss
> +    background-image: url(../images/ice-cream-back.jpg);
Добавлено

2023-01-13 16:12 UTC, Alexander0Yusov approved these changes

2023-01-13 16:12 UTC, merged

2023-01-13 16:13 UTC, Alexander0Yusov commented
well done

2023-01-13 16:13 UTC, Alexander0Yusov commented
all is in order

2023-01-13 16:13 UTC, Alexander0Yusov commented
+